### ISSUE TITLE
马娘名称的替换

### ISSUE THREAD

**Issue by kosakarin** [azmiao/umamusume_news#3]
很感谢大佬写的插件，在使用过程中发现部分名词翻译不是很好，于是自行稍微整理了下
主要是一些马的名称
    text = text.replace('ピックアップ', 'pick up')
    text = text.replace('ガチャ', '招募')
    text = text.replace('プリティーダービー', 'Pretty Derby')
    text = text.replace('サポートカード', 'support card')
    text = text.replace('ライスシャワー', 'rise shower')
    text = text.replace('スーパークリーク', '超级小海湾')
    text = text.replace('タマモクロス', '玉藻十字')
    text = text.replace('ゼンノロブロイ', '荒漠英雄')
    text = text.replace('スペシャルウィーク', '特别周')
    text = text.replace('サイレンススズカ', '无声铃鹿')
    text = text.replace('トウカイテイオー', '东海帝皇')
    text = text.replace('マルゼンスキー', '丸善斯基')
    text = text.replace('オグリキャップ', '小栗帽')
    text = text.replace('タイキシャトル', '大树快车')
    text = text.replace('メジロマックイーン', '目白麦昆')
    text = text.replace('シンボリルドルフ', '皇帝')
    text = text.replace('ゴールドシップ', '黄金船')
    text = text.replace('ウオッカ', '伏特加')
    text = text.replace('ダイワスカーレット', '大和赤骥')
    text = text.replace('グラスワンダー', '草上飞')   
    text = text.replace('エルコンドルパサー', '神鹰')
    text = text.replace('エアグルーヴ', '气槽')    
    text = text.replace('マヤノトップガン', '重砲')
    text = text.replace('メジロライアン', '目白赖恩')   
    text = text.replace('アグネスタキオン', '爱丽速子')
    text = text.replace('ウイニングチケット', '胜利奖券')       
    text = text.replace('サクラバクシンオー', '樱花进王')
    text = text.replace('ハルウララ', '乌拉拉')   
    text = text.replace('マチカネフクキタル', '待兼福来')
    text = text.replace('ナイスネイチャ', '优秀素质')    
    text = text.replace('キングヘイロー', '帝王光辉')
    text = text.replace('テイエムオペラオー', '好歌剧') 
    text = text.replace('ミホノブルボン', '美蒲波旁')
    text = text.replace('セイウンスカイ', '星云天空')
    text = text.replace('ファインモーション', '美妙姿势')
    text = text.replace('アイネスフウジン', '艾尼斯风神')
    text = text.replace('エアシャカール', '空中神宫')
    text = text.replace('ゴールドシチー', '黄金城市')
    text = text.replace('スマートファルコン', '醒目飞鹰')
    text = text.replace('ニシノフラワー', '西野花')
    text = text.replace('ビコーペガサス', '微光飞驹')
    text = text.replace('フジキセキ', '富士奇迹')
    text = text.replace('ヒシアマゾン', '亚马逊')
    text = text.replace('アグネスデジタル', '爱丽数码')
    text = text.replace('ビワハヤヒデ', '琵琶晨光')
    text = text.replace('マンハッタンカフェ', '曼城茶座')
    text = text.replace('ユキノビジン', '雪中美人')
    text = text.replace('エイシンフラッシュ', '荣进闪耀')
    text = text.replace('ナリタタイシン', '成田大进')
    text = text.replace('マーベラスサンデー', '美丽周日')
    text = text.replace('メイショウドトウ', '名将怒涛')
    text = text.replace('メジロドーベル', '目白多伯')
    text = text.replace('スイープトウショウ', '东商变革')
    text = text.replace('ツインターボ', '双涡轮')
    text = text.replace('ダイタクヘリオス', '大拓太阳神')
    text = text.replace('ナリタブライアン', '成田拜仁')
    text = text.replace('トーセンジョーダン', '东瀛佐敦')
    text = text.replace('ヒシアケボノ', '菱曙')
    text = text.replace('アドマイヤベガ', '爱慕织姬')
    text = text.replace('カレンチャン', '真机伶')
    text = text.replace('ゼンノロブロイ', '荒漠英雄')
    text = text.replace('マチカネタンホイザ', '诗歌剧')
    text = text.replace('イクノディクタス', '狄杜斯')
    text = text.replace('キタサンブラック', '北部玄驹')
    text = text.replace('サトノダイヤモンド', '里见光钻')
    text = text.replace('シーキングザパール', '采珠')
    text = text.replace('シンコウウインディ', '新光风')
    text = text.replace('ヤエノムテキ', '八重无敌')
    text = text.replace('バンブーメモリー', '青竹回忆')
    text = text.replace('イナリワン', '稻荷一')
    text = text.replace('カワカミプリンセス', '川上公主')
    text = text.replace('ミスターシービー', 'Mr CB')
    text = text.replace('サクラチヨノオー', '樱花千代')
    text = text.replace('シリウスシンボリ', '天狼象征')

**Comment by kosakarin** [comment]
然后刚刚想起来我把米浴写成rise shower了（
因为我本地额外做了一道回翻的步骤，米浴直接写'米浴'的话translate还是会将其翻译，所以我先用英文替换，等待拿到翻译文本后再将英文的文本改回中文

**Comment by azmiao** [comment]
> 然后刚刚想起来我把米浴写成rise shower了（
> 因为我本地额外做了一道回翻的步骤，米浴直接写'米浴'的话translate还是会将其翻译，所以我先用英文替换，等待拿到翻译文本后再将英文的文本改回中文

OK，晚上回去我再改改

**Comment by azmiao** [comment]
大概改了一下了，可以先试试，关于米浴这种的我这边正常翻译成米浴了，我也不知道为啥，可能是受服务器地区影响，如果你那仍然有问题可以试着去147增加翻译完的文本替换

**Comment by kosakarin** [comment]
好的
